package com.CSCI3130.gardenapp.util.db;

import com.google.firebase.database.FirebaseDatabase;

import java.util.Random;

/**
 * Utility test wrapper for DatabaseTaskWriter to ensure tasks are written under a unique
 * test branch.
 * @see com.CSCI3130.gardenapp.util.db.DatabaseTaskWriter
 * @author Liam Hebert
 */
public class DatabaseTaskTestWriter extends DatabaseTaskWriter {
    private final String test;

    /**
     * Constructor that injects a modified database into DatabaseTaskWriter
     */
    public DatabaseTaskTestWriter() {
        super(FirebaseDatabase.getInstance().getReference());
        Random rand = new Random();
        test = "test-" + rand.nextInt();
        db = db.getRoot().child(test).child("Tasks");
    }

    /**
     * Removes the autogenerated test tree in the database and all associated childs.
     * Should be used in the @After section of a test
     */
    public void clearDatabase(){
        db.getRoot().child(test).removeValue();
    }
}
