package com.CSCI3130.gardenapp.util.db;

import com.google.firebase.database.FirebaseDatabase;

import java.util.Random;

/**
 * Utility test wrapper for DatabaseTaskWriter to ensure tasks are written under a unique
 * test branch.
 * @see TaskDatabase
 * @author Liam Hebert
 */
public class TaskTestDatabase extends TaskDatabase {
    private final String test;

    /**
     * Constructor that injects a modified database into DatabaseTaskWriter
     */
    public TaskTestDatabase() {
        super(FirebaseDatabase.getInstance().getReference());
        Random rand = new Random();
        test = "test-" + rand.nextInt();
        dbWrite = dbWrite.getRoot().child(test).child("Tasks");
        dbRead = dbWrite;
    }

    /**
     * Removes the autogenerated test tree in the database and all associated childs.
     * Should be used in the @After section of a test
     */
    public void clearDatabase(){
        dbWrite.getRoot().child(test).removeValue();
    }
}
